TurneroIgle/Controllers/ReportesController.cs
using Rotativa;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TurneroIgle.Acceso_Datos;
using TurneroIgle.Models;
using TurneroIgle.Models.ViewModels;

namespace TurneroIgle.Controllers
{
    public class ReportesController : Controller
    {
        private List<SelectListItem> cargarFechasAnteriores()
        {
            List<Fecha> fecha = AD_fechas.fechaTurnosAnteriores();
            List<SelectListItem> lista = fecha.ConvertAll(f =>
            {
                return new SelectListItem()
                {
                    Text = f.Dia + ", " + f.FechaTurno.Date.ToShortDateString(),
                    Value = f.IdFecha.ToString(),
                    Selected = false
                };
            });

            return lista;

        }
        // GET: Reportes
        public ActionResult Index()
        {
            Fecha anterior = AD_fechas.fechaAnterior();
            ReporteVM reporte = new ReporteVM(anterior.IdFecha);
            Fecha turno = AD_fechas.fechaActual();
            ViewBag.Fecha = turno.ToString();
            ViewBag.items = cargarFechasAnteriores();
            return View(reporte);
        }
        public ActionResult Lista()
        {
            List<Turno> turnoActuales = AD_reportes.TurnosActualesConfirmados();
            return View(turnoActuales);
        }
        [HttpPost]
        public ActionResult Index(int IdFecha)
        {
            ReporteVM reporte = new ReporteVM(IdFecha);
            Fecha turno = AD_fechas.fechaActual();
            ViewBag.Fecha = turno.ToString();
            ViewBag.items = cargarFechasAnteriores();
            return View(reporte);
        }

    }

}

TurneroIgle/Views/Reportes/Index.cshtml
@model TurneroIgle.Models.ViewModels.ReporteVM
@{

    ViewBag.Title = "Administración";
    List<SelectListItem> items = (List<SelectListItem>)ViewBag.items;

}

<h2>Listas de Turnos</h2>

<div class="row">
    <div class="col-lg-6">
        <div class="col-lg-12">
            <div>
                <h3>
                    Turnos para el día @ViewBag.Fecha
                </h3>
            </div>
        </div>
        <div class=" col-lg-12">
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-horizontal">
                        <div class="form-group">
                            @Html.ActionLink("Imprimir", "Lista", "Reportes", htmlAttributes: new { @class = "btn btn-success" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th class="text-center">
                        Nombre
                    </th>
                    <th class="text-center">
                        Apellido
                    </th>
                    <th class="text-center">
                        Dni
                    </th>
                    <th class="text-center">
                        Telefono
                    </th>
                    <th class="text-center">
                        Acción
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var turno in Model.ListaAsisten)
                {
                    <tr class="text-center">
                        <td>
                            @turno.Nombre
                        </td>
                        <td>
                            @turno.Apellido
                        </td>
                        <td>
                            @turno.Dni
                        </td>
                        <td>
                            @turno.Telefono
                        </td>
                        <td>
                            No va
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="col-lg-6">
        <div class="col-lg-12">
            <div>
                <h3>
                    Reuniones anteriores
                </h3>
            </div>
        </div>
        <div class="col-lg-12">
            @using (Html.BeginForm())
            {
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-horizontal">
                            <div class="form-group">
                                <div class="col-md-9">
                                    @Html.DropDownList("IdFecha", items, htmlAttributes: new { @class = "form-control" })
                                </div>
                                <div class="col-md-3">
                                    <button class="btn btn-primary" type="submit">Buscar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th class="text-center">
                            Nombre
                        </th>
                        <th class="text-center">
                            Apellido
                        </th>
                        <th class="text-center">
                            Dni
                        </th>
                        <th class="text-center">
                            Telefono
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var turnoAnt in Model.ListaAnteriores)
                    {
                        <tr class="text-center">
                            <td>
                                @turnoAnt.Nombre
                            </td>
                            <td>
                                @turnoAnt.Apellido
                            </td>
                            <td>
                                @turnoAnt.Dni
                            </td>
                            <td>
                                @turnoAnt.Telefono
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="col-lg-12">
            <div>
                <h3>
                    En espera @ViewBag.Fecha
                </h3>
            </div>
        </div>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th class="text-center">
                        Nombre
                    </th>
                    <th class="text-center">
                        Apellido
                    </th>
                    <th class="text-center">
                        Dni
                    </th>
                    <th class="text-center">
                        Telefono
                    </th>
                    <th class="text-center">
                        Acción
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var turno in Model.ListaEspera)
                {
                    <tr class="text-center">
                        <td>
                            @turno.Nombre
                        </td>
                        <td>
                            @turno.Apellido
                        </td>
                        <td>
                            @turno.Dni
                        </td>
                        <td>
                            @turno.Telefono
                        </td>
                        <td>
                            No va
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>    
</div>

TurneroIgle/Views/Reportes/Lista.cshtml
@model List<TurneroIgle.Models.Turno>
@{
    Layout = null;
    ViewBag.Title = "Lista";
}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<h2>Lista confimados</h2>

<div class="row">
    <div class="col-lg-6">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th class="text-center">
                        Nombre
                    </th>
                    <th class="text-center">
                        Apellido
                    </th>
                    <th class="text-center">
                        Dni
                    </th>
                    <th class="text-center">
                        Telefono
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var turno in Model)
                {
                    <tr class="text-center">
                        <td>
                            @turno.Nombre
                        </td>
                        <td>
                            @turno.Apellido
                        </td>
                        <td>
                            @turno.Dni
                        </td>
                        <td>
                            @turno.Telefono
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>